# version: '3'
services:
  frontend:
    build:
      context: ./frontend
    container_name: haru-frontend-app
    ports:
      - "5174:5174"
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
    container_name: haru-backend-app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
